### ISSUE TITLE
New setup, RKE2, Nothing discovered

### ISSUE THREAD

**Issue by prashanthbgoud** [openclarity/openclarity#1029]
Hello All,

We see the issue listed here https://github.com/openclarity/openclarity/issues/898

Nothing is visible on the dashboard, the sock on the server is at path `/var/run/containerd/containerd.sock` which is a default value for cr-discovery. our data directory is `/var/lib/docker`.

<img width="1218" alt="Image" src="https://github.com/user-attachments/assets/b0144666-dda1-4668-b2a3-3e5bf68f3334" />

we have set containerRuntimePaths as below

```
  containerRuntimePaths:
    - name: containerd
      path: /var/run/containerd
      readOnly: true
    - name: docker
      path: /var/lib/docker
      readOnly: true
  containerSecurityContext:
    enabled: true
    runAsUser: 0
    runAsGroup: 0
    privileged: true
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
```

Logs:

```

time="2025-02-20T14:29:14Z" level=info msg="Loaded docker discoverer" app=openclarity
time="2025-02-20T14:29:14Z" level=warning msg="The docker discoverer is not ready. Skipping..." app=openclarity
time="2025-02-20T14:29:14Z" level=info msg="Loaded containerd discoverer" app=openclarity
time="2025-02-20T14:29:14Z" level=info msg="Server started listening on :8080..." app=openclarity
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.13.3
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8080
```

Could you help me debug?
