### ISSUE TITLE
All asses scans failed

### ISSUE THREAD

**Issue by finomen** [openclarity/openclarity#1031]
## Description

After clean install first full scan fails every single asset.

## Expected Behavior

Scan passed without errors

## Actual Behavior

In every asset scan some families are failed. Errors are similar but I could not found any logic in what fails where.

Failed SBOM
```
failed to process inputs for sbom: scan job "gomod" failed for input oci-archive:/mnt/snapshot/image.tar, reason: unsupported input type=oci-archive scan job "trivy" failed for input oci-archive:/mnt/snapshot/image.tar, reason: failed to configure trivy image options: unable to untar /mnt/snapshot/image.tar to temp directory: unable to untar /mnt/snapshot/image.tar to temp directory: unexpected EOF scan job "windows" failed for input oci-archive:/mnt/snapshot/image.tar, reason: skipping analyzing unsupported source type: oci-archive scan job "syft" failed for input oci-archive:/mnt/snapshot/image.tar, reason: failed to create source analyzer=syft: an error occurred attempting to resolve '/mnt/snapshot/image.tar': oci-archive: unexpected EOF

```

Failed misconfiguration but SBOM passed

```
failed to process inputs for misconfigurations: scan job "cisdocker" failed for input oci-archive:/mnt/snapshot/image.tar, reason: unsupported source type=oci-archive scan job "lynis" failed for input oci-archive:/mnt/snapshot/image.tar, reason: failed to convert input to filesystem: failed to expand container to rootfs directory: unable to get image: unable to parse image from src oci-archive:/mnt/snapshot/image.tar: unable to detect input for '/mnt/snapshot/image.tar', errs: unable to parse OCI directory as an image: unexpected media type for sha256:b899dbd1b9017b9a379f76ce5b40eead01a62762c4f2057eacef945c3c22d210: application/vnd.docker.distribution.manifest.list.v2+json
```

Failed secrets but SBOM passed

```
failed to process inputs for secrets: scan job "gitleaks" failed for input oci-archive:/mnt/snapshot/image.tar, reason: failed to convert input to filesystem: failed to expand container to rootfs directory: unable to get image: unable to parse image from src oci-archive:/mnt/snapshot/image.tar: unable to detect input for '/mnt/snapshot/image.tar', errs: unable to parse OCI directory as an image: unexpected media type for sha256:1e7657d997c5a48253bb8dc91ecee75b63018d16ff5e5797e5af367336bc8803: application/vnd.oci.image.index.v1+json
```

## Affected Version

Openclarity helm 1.1.3
Kubernetes v1.32.0 on baremetal (3 nodes, talos linux)

Configuration:

```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclarity
spec:
  interval: 5m
  chart:
    spec:
      chart: openclarity
      version: ">=v1.1.2 <v1.2.0"
      sourceRef:
        kind: HelmRepository
        name: openclarity
      interval: 1m
  values:
    apiserver:
      replicas: 2
      database:
        postgresql:
          enabled: false
        externalPostgresql:
          enabled: true
          host: postgresql-rw
          auth:
            existingSecret: openclarity-db-secret
    orchestrator:
      replicas: 2
      provider: kubernetes
      serviceAccount:
        automountServiceAccountToken: true
    ui:
      replicas: 2
    uibackend:
      replicas: 2
    crDiscoveryServer:
      containerRuntimePaths:
      - name: containerd
        path: /var/run/containerd
        readOnly: true
      - name: k3s-containerd
        path: /run/k3s/containerd
        readOnly: true
    gateway:
      replicas: 2
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: 30m
          nginx.ingress.kubernetes.io/proxy-buffering: 'on'
          nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
          nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 1024m
          nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
          nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
          nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
          nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
          nginx.ingress.kubernetes.io/configuration-snippet: |
              auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
              access_by_lua_block {
                if ngx.var.name_upstream_1 ~= "" then
                  ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
              end
              }
        ingressClassName: nginx
        hosts:
        - host: openclarity.XXX.YYY
        tls:
        - secretName: openclarity-cert
          hosts:
          - openclarity.XXX.YYY
```

## Steps to Reproduce

1. Install on kubernetes using helm
2. Scan 

## Checklist

- [X] I have verified this does not duplicate an existing issue (https://github.com/openclarity/openclarity/issues/1027 may be related but not the same)
