### ISSUE TITLE
Database crashing on second run

### ISSUE THREAD

**Issue by ppapp92** [openclarity/openclarity#1092]
## Description

I'm having issue with errors while running the scans. I'm running OpenClarity in K8s. The first run works fine on about 1300 assets. Once I start the second run I get all sort of database errors causing it to crash and become unstable. Only way to recover is to delete everything and redeploy.

## Expected Behavior

Second and subsequent runs should work normally.

## Actual Behavior

I've tried a few different configurations.

1. Using the default Helm Chart values the `apiserver` starts to get database errors related to not having enough connects. On the second run it will OOM continuously
2. Using modified in-cluster postgres config the connection errors are gone and first run works fine. On the second run the DB starts throwing 'FATAL:  the database system is shutting down' errors and app become unstable

```
postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRESQL_MAX_CONNECTIONS
        value: "5000"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 3
        memory: 3Gi
apiserver:
  replicas: 1
  database:
    postgresql:
      enabled: true
```
3. Using sqlite, on the second run the `apiserver` starts throwing errors related to unstable DB

## Affected Version

1.1.3

## Steps to Reproduce

1. Deploy OpenClarity into K8s using any of the above DB configurations
2. Run scan once
3. Run scan again
4. DB will start to error

**Comment by Spenhouet** [comment]
I had a lot of problems with this as well. The database kept on getting unstable and then running into restart loops with liveness probes being unsuccessful.

I increase the resources, timeout config and max connections.

For now, this config did not crash (yet):

```yaml
      postgresql:
          global:
            defaultStorageClass: "rook-cephfs"
          primary:
            persistence:
              enabled: true
              storageClass: "rook-cephfs"
              size: 8Gi
              accessModes:
                - ReadWriteOnce
            # Increase resources to prevent probe timeouts
            resources:
              requests:
                cpu: 2000m      # 2 CPU cores
                memory: 2Gi     # 2GB RAM
              limits:
                cpu: 4000m      # 4 CPU cores
                memory: 8Gi     # 8GB RAM
            # Much more tolerant probe settings
            livenessProbe:
              timeoutSeconds: 30
              periodSeconds: 30
              failureThreshold: 10
              initialDelaySeconds: 60
            readinessProbe:
              timeoutSeconds: 30
              periodSeconds: 15
              failureThreshold: 6
            readinessProbe:
              timeoutSeconds: 10
              periodSeconds: 10
              failureThreshold: 6
            # PostgreSQL configuration to handle more connections
            extendedConfiguration: |
              max_connections = 500
              shared_buffers = 512MB
              effective_cache_size = 4GB
              work_mem = 8MB
              maintenance_work_mem = 128MB
```

But I'm also wondering why it comes with a default config which seems to send the DB into a crash loop.

I as well seemed to have to completely nuke the postgress instance to recover it from it's faulty state. Which is not promissing for should we decide to use openclarity.
