### ISSUE TITLE
Failed to fetch kubeclarity helm charts.

### ISSUE THREAD

**Issue by kosukeoya** [openclarity/openclarity#728]
#### What happened:

Failed to fetch helm charts.
- `Error: failed to fetch https://github.com/openclarity/kubeclarity/releases/download/kubeclarity-v2.15.1-helm/kubeclarity-v2.15.1.tgz : 404 Not Found`

#### What you expected to happen:

Successful fetch.

#### How to reproduce it (as minimally and precisely as possible):

debug_kubeclarity/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kubeclarity
  namespace: ops
  includeCRDs: false
  releaseName: kubeclarity
  version: v2.15.1
  repo: https://openclarity.github.io/kubeclarity
```

`kustomize build --enable-helm ./debug_kubeclarity`

#### Are there any error messages in KubeClarity logs?
(e.g. `kubectl logs -n kubeclarity --selector=app=kubeclarity`)

#### Environment:
- Kubernetes version (use `kubectl version --short`):
- Helm version (use `helm version`):
   - v3.15.3
- KubeClarity version (use `kubectl -n kubeclarity exec deploy/kubeclarity -- ./backend version`)
- KubeClarity Helm Chart version (use `helm -n kubeclarity list`)
   - v2.15.1
- Cloud provider or hardware configuration:
- Others:
   - kustomize: v5.3.0

Same issue as https://github.com/openclarity/kubeclarity/issues/23
